# This file will be generated by nixos-generate-config
# For now, here's a template with common hardware support

{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  # Kernel modules
  boot.initrd.availableKernelModules = ["ext4" "xhci_pci" "ahci" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ]; # i5-4690K uses Intel VT-x
  boot.extraModulePackages = [ ];

  # Filesystems - REPLACE WITH YOUR ACTUAL CONFIGURATION
  fileSystems."/" = {
    device = "/dev/sdb2";
    fsType = "ext4";
  };

  swapDevices = [ ];

  # Hardware support
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  # Or for AMD:
  # hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  
  # Video drivers - NVIDIA GTX 1080 Ti
  services.xserver.videoDrivers = [ "nvidia" ];
  
  # NVIDIA Configuration for GTX 1080 Ti (Pascal generation)
  hardware.nvidia = {
    # Use closed source drivers for Pascal GPU
    open = false;
    
    # Enable modesetting for better Wayland compatibility
    modesetting.enable = true;
    
    # Power management (optional, mainly for laptops)
    powerManagement.enable = false;
    
    # Use the stable driver
    package = config.boot.kernelPackages.nvidiaPackages.stable;
  };
  
  # Enable firmware
  hardware.enableRedistributableFirmware = true;
}
