# This file will be generated by nixos-generate-config
# For now, here's a template with common hardware support

{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  # Kernel modules
  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ]; # i5-4690K uses Intel VT-x
  boot.extraModulePackages = [ ];

  # Filesystems - REPLACE WITH YOUR ACTUAL CONFIGURATION
  fileSystems."/" = {
    device = "/dev/disk/by-label/nixos";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-label/boot";
    fsType = "vfat";
  };

  swapDevices = [ ];

  # Hardware support
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  # Or for AMD:
  # hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  
  # Video drivers - covers your Guix video driver list
  services.xserver.videoDrivers = [ "amdgpu" "nvidia" "nouveau" "modesetting" ];
  
  # Enable firmware
  hardware.enableRedistributableFirmware = true;
}